spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;INIT=CREATE SCHEMA IF NOT EXISTS drones
    driverClassName: org.h2.Driver
    password: password
  h2:
    console:
      enabled: 'true'
  jpa:
    properties:
      hibernate:
        default_schema: drones
        format_sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8081
  servlet:
    context-path: /api

